Update pointcloud.py
Hello,
I just started with Open3D and currently doing the basic tutorials and got the following error message when trying out the pointcloud.py one:
" File "pointcloud.py", line 38, in <module>
    chair = vol.o3d.geometry.crop_point_cloud(pcd)
AttributeError: 'open3d.open3d.visualization.SelectionPolygonVolume' object has no attribute 'o3d'
"
Therefore I changed line 38 and it works out fine now