Unit Testing -part 2- (#330)
* removed system file.

* first draft of Open3D unit testing.
Unit test naming: <original file name>_unittest.cpp.
No directory structure for now, all tests are laid flat in src/UnitTest.
When a new unit test file is created add it to /src/UnitTest/CmakeLists.txt in order to include it in the unitTest binary.

* the Geometry class is using a protected constructor - can't test it directly.
Test Image instead as the first example.

* use three::Image as the first example.

* fix build. add simple test.
note <undefined reference to vtable for three::Image> error when uncommenting the line about image.width_.

* added more assertions to the DefaultConstructor test case.

* added more asserts.

* Open3D_BUILD_UNIT_TESTS will be OFF by default.
The reason is that it depends on the googletest which doesn't have a proper install package and requires building and copying files around before building the unit tests.

* added basic documentation for unit testing in 'Compilation Options'.

* minor correction of unit test build instructions.

* updated gtest installation instructions.
this works on mac also.

* fix installing the gtest headers.

* tested and works on both macOS and Ubuntu Linux.

* various options for signaling 'Not implemented.'

* rename file: remove 'unittest' suffix.

* fix build.

* cleanup.

* cleanup.

* added unit test templates for all three libraries: Core, IO and Visualization.

* enable unit test build on macOS and Linux CI.
make sure the unit test build is disabled on Windows.

* install gtest 1.8.0 before building the unit tests.

* add line terminators after each bash instruction.

* added scripts for un/installing gtest.

* added line terminator.

* fixed syntax error.

* test local repo travis CI.

* separate linux and osx paths for gtest installation.

* updated documentation to show a simpler option for installing gtest: /util/scripts/install-gtest.sh.