debugging
can't call DrawGeometriesWithAnimationCallback() because

RuntimeError: return_value_policy = move, but the object is neither
movable nor copyable!